// Generated by CoffeeScript 1.3.3
(function() {
  var $, methods;

  $ = jQuery;

  methods = {
    init: function(allOptions) {
      var objectData;
      objectData = this.data('chart');
      if (!objectData) {
        this.data('chart', {
          url: allOptions.url,
          chartType: allOptions.chartType,
          options: allOptions.options,
          columnTitles: allOptions.columnTitles,
          target: this,
          chartData: new google.visualization.DataTable(),
          jsonData: allOptions.jsonData,
          chartDrawn: false
        });
      }
      return methods.update.apply(this, arguments);
    },
    update: function() {
      var objectData;
      objectData = this.data('chart');
      if (objectData.url === void 0) {
        return methods.parse.apply(this, arguments);
      } else {
        return $.getJSON(objectData.url, function(data) {
          objectData.jsonData = data;
          return methods.parse.apply(this, arguments);
        });
      }
    },
    parse: function() {
      var objectData;
      objectData = this.data('chart');
      if (!(objectData.columnTitles === void 0) && (!(objectData.url === void 0) || ((objectData.url === void 0) && !objectData.chartDrawn))) {
        objectData.jsonData.splice(0, 0, objectData.columnTitles);
      }
      objectData.chartData = google.visualization.arrayToDataTable(objectData.jsonData);
      return methods.draw.apply(this, arguments);
    },
    draw: function() {
      var allDefaults, barDefaults, lineDefaults, objectData, pieDefaults;
      objectData = this.data('chart');
      allDefaults = {
        width: 500,
        height: 300,
        animation: {
          duration: 1000,
          easing: 'inAndOut'
        }
      };
      if (objectData.chartType === 'bar') {
        barDefaults = {
          legend: 'none',
          hAxis: {
            minValue: 0
          }
        };
        barDefaults = $.extend(allDefaults, barDefaults);
        objectData.options = $.extend(barDefaults, objectData.options);
        objectData.chart = new google.visualization.BarChart(objectData.target.get(0));
      } else if (objectData.chartType === 'line') {
        lineDefaults = {};
        lineDefaults = $.extend(allDefaults, lineDefaults);
        objectData.options = $.extend(lineDefaults, objectData.options);
        objectData.chart = new google.visualization.LineChart(objectData.target.get(0));
      } else if (objectData.chartType === 'pie') {
        pieDefaults = {};
        pieDefaults = $.extend(allDefaults, pieDefaults);
        objectData.options = $.extend(pieDefaults, objectData.options);
        objectData.chart = new google.visualization.PieChart(objectData.target.get(0));
      }
      objectData.chart.draw(objectData.chartData, objectData.options);
      return objectData.chartDrawn = true;
    }
  };

  $.fn.chart = function(method) {
    if (methods[method]) {
      return methods[method].apply(this, Array.prototype.slice.call(arguments, 1));
    } else if (typeof method === 'object' || !method) {
      return methods.init.apply(this, arguments);
    } else {
      return $.error('Method ' + method + ' does not exist on jQuery.chart');
    }
  };

}).call(this);
